chore: publish version 0.1.6
supabase-community/gotrue-dart pull request #62
Opened 2022-02-28 18:14 UTC by DanMossa

2022-02-28 18:15 UTC, DanMossa commented
@bdlukaa Does this look alright?

2022-03-01 10:50 UTC, derakula reviewed
up up asap with supabase flutter.. we need native google signin

2022-03-01 11:27 UTC, dshukertjr requested changes
Just one small change within the changelog, and  it looks good to me!

2022-03-01 11:27 UTC, dshukertjr commented on CHANGELOG.md
We can get rid of this `[next]` piece. This is just a placeholder for when we publish new version.

2022-03-01 19:24 UTC, DanMossa commented
@dshukertjr Done!

2022-03-03 13:35 UTC, dshukertjr approved these changes
LGTM!

2022-03-03 13:35 UTC, merged